name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: FTP Mirror
      uses: sand4rt/ftp-deployer@v1.7
      with:
        # FTP Server.
        host: ${{ secrets.FTP_HOST }}
        # FTP User.
        username: ${{ secrets.FTP_USER }}
        # FTP Password.
        password: ${{ secrets.FTP_PASSWORD }}
        # Local directory.
        local_folder: ${{ github.workspace }}/_site
        # Remote directory.
        remote_folder: /
        cleanup: true
